Traceback (most recent call last):
  File "app.py", line 101, in <module>
    decryptkey = derive_key(decrypt_pass)
  File "app.py", line 97, in derive_key
    key = base64.urlsafe_b64encode(kdf.derive(password.encode()))
AttributeError: 'NoneType' object has no attribute 'encode'
g on http://131.111.179.99:21389
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 115-403-946
Password is correct!
Traceback (most recent call last):
  File "/public/home/wp280/public_html/dcbc/app.py", line 1853, in <module>
    app.run(port=21389,host='0.0.0.0', debug=True)
  File "/home/wp280/Flaskenv/lib/python3.8/site-packages/flask/app.py", line 625, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/wp280/Flaskenv/lib/python3.8/site-packages/werkzeug/serving.py", line 1113, in run_simple
    run_with_reloader(
  File "/home/wp280/Flaskenv/lib/python3.8/site-packages/werkzeug/_reloader.py", line 448, in run_with_reloader
    ensure_echo_on()
  File "/home/wp280/Flaskenv/lib/python3.8/site-packages/werkzeug/_reloader.py", line 428, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (5, 'Input/output error')
Password is correct!
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 21389 is in use by another program. Either identify and stop that program, or start the server with a different port.
